// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW5Ci0DdPPQxkl5llhEbpDaWLD28yI5Z4',
    appId: '1:52216104618:android:f2ee8839af53bd2a4872d3',
    messagingSenderId: '52216104618',
    projectId: 'ecommerce-1c098',
    storageBucket: 'ecommerce-1c098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDroq65yJ6hFx-ghfWtBl30hJ9-UuXjvfw',
    appId: '1:52216104618:ios:f2ad950e606c39d44872d3',
    messagingSenderId: '52216104618',
    projectId: 'ecommerce-1c098',
    storageBucket: 'ecommerce-1c098.firebasestorage.app',
    androidClientId: '52216104618-2u8qse2aduot5p8h8cvpp4ovam0ttcs8.apps.googleusercontent.com',
    iosClientId: '52216104618-pvt7c9v3j8fra4fquv8vc389k9emfbfn.apps.googleusercontent.com',
    iosBundleId: 'com.itsharks.ecommerceApp',
  );

}